<?php

/**
 * Add new calculator hero keys and trust section to all language files.
 * Run: php scripts/add-calculator-hero-keys.php
 */

$basePath = dirname(__DIR__) . '/lang';

$translations = [
    'bg' => [
        'calculator' => [
            'add_vat_mode' => 'Добави ДДС',
            'remove_vat_mode' => 'Извади ДДС',
            'realtime_rates' => 'Ставки в реално време',
            'official_eu_data' => 'Официални данни на ЕС',
            'country_label' => 'Държава',
            'amount_incl_vat' => 'Сума (с ДДС)',
            'amount_excl_vat' => 'Сума (без ДДС)',
            'select_country' => 'Изберете държава',
            'search_countries' => 'Търсене на държави...',
            'no_countries_found' => 'Няма намерени държави',
            'calculate_btn' => 'Изчисли',
            'rate_label' => 'Ставка',
            'custom_label' => 'Персонализирана',
            'custom_percent' => 'Персонализирана %',
            'vat_label' => 'ДДС (:rate%)',
            'total_incl_vat' => 'Общо (с ДДС)',
            'you_entered_incl_vat' => 'Въведохте (с ДДС)',
            'share_details' => 'Споделяне и подробности',
            'full_calculator' => 'Пълен калкулатор',
            'eu_countries_count' => '27 държави от ЕС',
            'free_label' => '100% безплатно',
            'no_signup' => 'Без регистрация',
            'recent_calculations' => 'Последни изчисления',
            'clear_all' => 'Изчисти всичко',
            'show_more' => 'Покажи още :count',
            'show_less' => 'Покажи по-малко',
            'plus_vat' => '+ ДДС',
            'minus_vat' => '− ДДС',
        ],
        'trust' => [
            'official_ec_data' => 'Официални данни на Европейската комисия',
            'always_free' => 'Винаги безплатно',
            'all_27_countries' => 'Всички 27 държави от ЕС',
            'no_signup_required' => 'Без регистрация',
        ],
    ],
    'cs' => [
        'calculator' => [
            'add_vat_mode' => 'Přidat DPH',
            'remove_vat_mode' => 'Odebrat DPH',
            'realtime_rates' => 'Sazby v reálném čase',
            'official_eu_data' => 'Oficiální data EU',
            'country_label' => 'Země',
            'amount_incl_vat' => 'Částka (s DPH)',
            'amount_excl_vat' => 'Částka (bez DPH)',
            'select_country' => 'Vyberte zemi',
            'search_countries' => 'Hledat země...',
            'no_countries_found' => 'Žádné země nenalezeny',
            'calculate_btn' => 'Vypočítat',
            'rate_label' => 'Sazba',
            'custom_label' => 'Vlastní',
            'custom_percent' => 'Vlastní %',
            'vat_label' => 'DPH (:rate%)',
            'total_incl_vat' => 'Celkem (s DPH)',
            'you_entered_incl_vat' => 'Zadali jste (s DPH)',
            'share_details' => 'Sdílet a podrobnosti',
            'full_calculator' => 'Plná kalkulačka',
            'eu_countries_count' => '27 zemí EU',
            'free_label' => '100% zdarma',
            'no_signup' => 'Bez registrace',
            'recent_calculations' => 'Nedávné výpočty',
            'clear_all' => 'Vymazat vše',
            'show_more' => 'Zobrazit dalších :count',
            'show_less' => 'Zobrazit méně',
            'plus_vat' => '+ DPH',
            'minus_vat' => '− DPH',
        ],
        'trust' => [
            'official_ec_data' => 'Oficiální data Evropské komise',
            'always_free' => 'Vždy zdarma',
            'all_27_countries' => 'Všech 27 zemí EU',
            'no_signup_required' => 'Bez registrace',
        ],
    ],
    'da' => [
        'calculator' => [
            'add_vat_mode' => 'Tilføj moms',
            'remove_vat_mode' => 'Fjern moms',
            'realtime_rates' => 'Realtidssatser',
            'official_eu_data' => 'Officielle EU-data',
            'country_label' => 'Land',
            'amount_incl_vat' => 'Beløb (inkl. moms)',
            'amount_excl_vat' => 'Beløb (ekskl. moms)',
            'select_country' => 'Vælg land',
            'search_countries' => 'Søg efter lande...',
            'no_countries_found' => 'Ingen lande fundet',
            'calculate_btn' => 'Beregn',
            'rate_label' => 'Sats',
            'custom_label' => 'Brugerdefineret',
            'custom_percent' => 'Brugerdefineret %',
            'vat_label' => 'Moms (:rate%)',
            'total_incl_vat' => 'Total (inkl. moms)',
            'you_entered_incl_vat' => 'Du indtastede (inkl. moms)',
            'share_details' => 'Del og detaljer',
            'full_calculator' => 'Fuld beregner',
            'eu_countries_count' => '27 EU-lande',
            'free_label' => '100% gratis',
            'no_signup' => 'Ingen tilmelding nødvendig',
            'recent_calculations' => 'Seneste beregninger',
            'clear_all' => 'Ryd alt',
            'show_more' => 'Vis :count mere',
            'show_less' => 'Vis mindre',
            'plus_vat' => '+ moms',
            'minus_vat' => '− moms',
        ],
        'trust' => [
            'official_ec_data' => 'Officielle data fra Europa-Kommissionen',
            'always_free' => 'Altid gratis',
            'all_27_countries' => 'Alle 27 EU-lande',
            'no_signup_required' => 'Ingen tilmelding nødvendig',
        ],
    ],
    'de' => [
        'calculator' => [
            'add_vat_mode' => 'MwSt hinzufügen',
            'remove_vat_mode' => 'MwSt entfernen',
            'realtime_rates' => 'Echtzeit-Sätze',
            'official_eu_data' => 'Offizielle EU-Daten',
            'country_label' => 'Land',
            'amount_incl_vat' => 'Betrag (inkl. MwSt)',
            'amount_excl_vat' => 'Betrag (exkl. MwSt)',
            'select_country' => 'Land auswählen',
            'search_countries' => 'Länder suchen...',
            'no_countries_found' => 'Keine Länder gefunden',
            'calculate_btn' => 'Berechnen',
            'rate_label' => 'Satz',
            'custom_label' => 'Benutzerdefiniert',
            'custom_percent' => 'Benutzerdefiniert %',
            'vat_label' => 'MwSt (:rate%)',
            'total_incl_vat' => 'Gesamt (inkl. MwSt)',
            'you_entered_incl_vat' => 'Sie haben eingegeben (inkl. MwSt)',
            'share_details' => 'Teilen & Details',
            'full_calculator' => 'Voller Rechner',
            'eu_countries_count' => '27 EU-Länder',
            'free_label' => '100% kostenlos',
            'no_signup' => 'Keine Anmeldung erforderlich',
            'recent_calculations' => 'Letzte Berechnungen',
            'clear_all' => 'Alles löschen',
            'show_more' => ':count weitere anzeigen',
            'show_less' => 'Weniger anzeigen',
            'plus_vat' => '+ MwSt',
            'minus_vat' => '− MwSt',
        ],
        'trust' => [
            'official_ec_data' => 'Offizielle Daten der Europäischen Kommission',
            'always_free' => 'Immer kostenlos',
            'all_27_countries' => 'Alle 27 EU-Länder',
            'no_signup_required' => 'Keine Anmeldung erforderlich',
        ],
    ],
    'el' => [
        'calculator' => [
            'add_vat_mode' => 'Προσθήκη ΦΠΑ',
            'remove_vat_mode' => 'Αφαίρεση ΦΠΑ',
            'realtime_rates' => 'Συντελεστές σε πραγματικό χρόνο',
            'official_eu_data' => 'Επίσημα δεδομένα ΕΕ',
            'country_label' => 'Χώρα',
            'amount_incl_vat' => 'Ποσό (με ΦΠΑ)',
            'amount_excl_vat' => 'Ποσό (χωρίς ΦΠΑ)',
            'select_country' => 'Επιλέξτε χώρα',
            'search_countries' => 'Αναζήτηση χωρών...',
            'no_countries_found' => 'Δεν βρέθηκαν χώρες',
            'calculate_btn' => 'Υπολογισμός',
            'rate_label' => 'Συντελεστής',
            'custom_label' => 'Προσαρμοσμένος',
            'custom_percent' => 'Προσαρμοσμένο %',
            'vat_label' => 'ΦΠΑ (:rate%)',
            'total_incl_vat' => 'Σύνολο (με ΦΠΑ)',
            'you_entered_incl_vat' => 'Εισαγάγατε (με ΦΠΑ)',
            'share_details' => 'Κοινοποίηση & Λεπτομέρειες',
            'full_calculator' => 'Πλήρης υπολογιστής',
            'eu_countries_count' => '27 χώρες ΕΕ',
            'free_label' => '100% δωρεάν',
            'no_signup' => 'Χωρίς εγγραφή',
            'recent_calculations' => 'Πρόσφατοι υπολογισμοί',
            'clear_all' => 'Εκκαθάριση όλων',
            'show_more' => 'Εμφάνιση :count ακόμη',
            'show_less' => 'Εμφάνιση λιγότερων',
            'plus_vat' => '+ ΦΠΑ',
            'minus_vat' => '− ΦΠΑ',
        ],
        'trust' => [
            'official_ec_data' => 'Επίσημα δεδομένα Ευρωπαϊκής Επιτροπής',
            'always_free' => 'Πάντα δωρεάν',
            'all_27_countries' => 'Όλες οι 27 χώρες ΕΕ',
            'no_signup_required' => 'Χωρίς εγγραφή',
        ],
    ],
    'es' => [
        'calculator' => [
            'add_vat_mode' => 'Añadir IVA',
            'remove_vat_mode' => 'Quitar IVA',
            'realtime_rates' => 'Tasas en tiempo real',
            'official_eu_data' => 'Datos oficiales de la UE',
            'country_label' => 'País',
            'amount_incl_vat' => 'Importe (IVA incluido)',
            'amount_excl_vat' => 'Importe (sin IVA)',
            'select_country' => 'Seleccionar país',
            'search_countries' => 'Buscar países...',
            'no_countries_found' => 'No se encontraron países',
            'calculate_btn' => 'Calcular',
            'rate_label' => 'Tipo',
            'custom_label' => 'Personalizado',
            'custom_percent' => 'Personalizado %',
            'vat_label' => 'IVA (:rate%)',
            'total_incl_vat' => 'Total (IVA incluido)',
            'you_entered_incl_vat' => 'Introdujo (IVA incluido)',
            'share_details' => 'Compartir y detalles',
            'full_calculator' => 'Calculadora completa',
            'eu_countries_count' => '27 países de la UE',
            'free_label' => '100% gratuito',
            'no_signup' => 'Sin registro',
            'recent_calculations' => 'Cálculos recientes',
            'clear_all' => 'Borrar todo',
            'show_more' => 'Mostrar :count más',
            'show_less' => 'Mostrar menos',
            'plus_vat' => '+ IVA',
            'minus_vat' => '− IVA',
        ],
        'trust' => [
            'official_ec_data' => 'Datos oficiales de la Comisión Europea',
            'always_free' => 'Siempre gratuito',
            'all_27_countries' => 'Los 27 países de la UE',
            'no_signup_required' => 'Sin registro',
        ],
    ],
    'et' => [
        'calculator' => [
            'add_vat_mode' => 'Lisa käibemaks',
            'remove_vat_mode' => 'Eemalda käibemaks',
            'realtime_rates' => 'Reaalajas määrad',
            'official_eu_data' => 'Ametlikud EL-i andmed',
            'country_label' => 'Riik',
            'amount_incl_vat' => 'Summa (koos käibemaksuga)',
            'amount_excl_vat' => 'Summa (ilma käibemaksuta)',
            'select_country' => 'Valige riik',
            'search_countries' => 'Otsi riike...',
            'no_countries_found' => 'Riike ei leitud',
            'calculate_btn' => 'Arvuta',
            'rate_label' => 'Määr',
            'custom_label' => 'Kohandatud',
            'custom_percent' => 'Kohandatud %',
            'vat_label' => 'Käibemaks (:rate%)',
            'total_incl_vat' => 'Kokku (koos käibemaksuga)',
            'you_entered_incl_vat' => 'Sisestasite (koos käibemaksuga)',
            'share_details' => 'Jaga ja üksikasjad',
            'full_calculator' => 'Täiskalkulaator',
            'eu_countries_count' => '27 EL-i riiki',
            'free_label' => '100% tasuta',
            'no_signup' => 'Registreerimine pole vajalik',
            'recent_calculations' => 'Viimased arvutused',
            'clear_all' => 'Tühjenda kõik',
            'show_more' => 'Näita veel :count',
            'show_less' => 'Näita vähem',
            'plus_vat' => '+ käibemaks',
            'minus_vat' => '− käibemaks',
        ],
        'trust' => [
            'official_ec_data' => 'Ametlikud Euroopa Komisjoni andmed',
            'always_free' => 'Alati tasuta',
            'all_27_countries' => 'Kõik 27 EL-i riiki',
            'no_signup_required' => 'Registreerimine pole vajalik',
        ],
    ],
    'fi' => [
        'calculator' => [
            'add_vat_mode' => 'Lisää ALV',
            'remove_vat_mode' => 'Poista ALV',
            'realtime_rates' => 'Reaaliaikaiset verokannot',
            'official_eu_data' => 'EU:n viralliset tiedot',
            'country_label' => 'Maa',
            'amount_incl_vat' => 'Summa (sis. ALV)',
            'amount_excl_vat' => 'Summa (ilman ALV)',
            'select_country' => 'Valitse maa',
            'search_countries' => 'Hae maita...',
            'no_countries_found' => 'Maita ei löytynyt',
            'calculate_btn' => 'Laske',
            'rate_label' => 'Verokanta',
            'custom_label' => 'Mukautettu',
            'custom_percent' => 'Mukautettu %',
            'vat_label' => 'ALV (:rate%)',
            'total_incl_vat' => 'Yhteensä (sis. ALV)',
            'you_entered_incl_vat' => 'Syötit (sis. ALV)',
            'share_details' => 'Jaa ja tiedot',
            'full_calculator' => 'Täysi laskin',
            'eu_countries_count' => '27 EU-maata',
            'free_label' => '100% ilmainen',
            'no_signup' => 'Ei rekisteröitymistä',
            'recent_calculations' => 'Viimeisimmät laskut',
            'clear_all' => 'Tyhjennä kaikki',
            'show_more' => 'Näytä :count lisää',
            'show_less' => 'Näytä vähemmän',
            'plus_vat' => '+ ALV',
            'minus_vat' => '− ALV',
        ],
        'trust' => [
            'official_ec_data' => 'Euroopan komission viralliset tiedot',
            'always_free' => 'Aina ilmainen',
            'all_27_countries' => 'Kaikki 27 EU-maata',
            'no_signup_required' => 'Ei rekisteröitymistä',
        ],
    ],
    'fr' => [
        'calculator' => [
            'add_vat_mode' => 'Ajouter la TVA',
            'remove_vat_mode' => 'Retirer la TVA',
            'realtime_rates' => 'Taux en temps réel',
            'official_eu_data' => 'Données officielles de l\'UE',
            'country_label' => 'Pays',
            'amount_incl_vat' => 'Montant (TTC)',
            'amount_excl_vat' => 'Montant (HT)',
            'select_country' => 'Sélectionner un pays',
            'search_countries' => 'Rechercher des pays...',
            'no_countries_found' => 'Aucun pays trouvé',
            'calculate_btn' => 'Calculer',
            'rate_label' => 'Taux',
            'custom_label' => 'Personnalisé',
            'custom_percent' => 'Personnalisé %',
            'vat_label' => 'TVA (:rate%)',
            'total_incl_vat' => 'Total (TTC)',
            'you_entered_incl_vat' => 'Vous avez saisi (TTC)',
            'share_details' => 'Partager et détails',
            'full_calculator' => 'Calculateur complet',
            'eu_countries_count' => '27 pays de l\'UE',
            'free_label' => '100% gratuit',
            'no_signup' => 'Sans inscription',
            'recent_calculations' => 'Calculs récents',
            'clear_all' => 'Tout effacer',
            'show_more' => 'Afficher :count de plus',
            'show_less' => 'Afficher moins',
            'plus_vat' => '+ TVA',
            'minus_vat' => '− TVA',
        ],
        'trust' => [
            'official_ec_data' => 'Données officielles de la Commission européenne',
            'always_free' => 'Toujours gratuit',
            'all_27_countries' => 'Les 27 pays de l\'UE',
            'no_signup_required' => 'Sans inscription',
        ],
    ],
    'ga' => [
        'calculator' => [
            'add_vat_mode' => 'Cuir CBL leis',
            'remove_vat_mode' => 'Bain CBL',
            'realtime_rates' => 'Rátaí fíor-ama',
            'official_eu_data' => 'Sonraí oifigiúla an AE',
            'country_label' => 'Tír',
            'amount_incl_vat' => 'Méid (CBL san áireamh)',
            'amount_excl_vat' => 'Méid (CBL as an áireamh)',
            'select_country' => 'Roghnaigh tír',
            'search_countries' => 'Cuardaigh tíortha...',
            'no_countries_found' => 'Níor aimsíodh aon tír',
            'calculate_btn' => 'Ríomh',
            'rate_label' => 'Ráta',
            'custom_label' => 'Saincheaptha',
            'custom_percent' => 'Saincheaptha %',
            'vat_label' => 'CBL (:rate%)',
            'total_incl_vat' => 'Iomlán (CBL san áireamh)',
            'you_entered_incl_vat' => 'Chuir tú isteach (CBL san áireamh)',
            'share_details' => 'Roinn & Sonraí',
            'full_calculator' => 'Áireamhán iomlán',
            'eu_countries_count' => '27 tír an AE',
            'free_label' => '100% saor in aisce',
            'no_signup' => 'Gan clárú riachtanach',
            'recent_calculations' => 'Ríomhanna le déanaí',
            'clear_all' => 'Glan ar fad',
            'show_more' => 'Taispeáin :count eile',
            'show_less' => 'Taispeáin níos lú',
            'plus_vat' => '+ CBL',
            'minus_vat' => '− CBL',
        ],
        'trust' => [
            'official_ec_data' => 'Sonraí oifigiúla an Choimisiúin Eorpaigh',
            'always_free' => 'Saor in aisce i gcónaí',
            'all_27_countries' => 'Gach ceann de 27 tír an AE',
            'no_signup_required' => 'Gan clárú riachtanach',
        ],
    ],
    'hr' => [
        'calculator' => [
            'add_vat_mode' => 'Dodaj PDV',
            'remove_vat_mode' => 'Ukloni PDV',
            'realtime_rates' => 'Stope u stvarnom vremenu',
            'official_eu_data' => 'Službeni podaci EU-a',
            'country_label' => 'Država',
            'amount_incl_vat' => 'Iznos (s PDV-om)',
            'amount_excl_vat' => 'Iznos (bez PDV-a)',
            'select_country' => 'Odaberite državu',
            'search_countries' => 'Pretraži države...',
            'no_countries_found' => 'Države nisu pronađene',
            'calculate_btn' => 'Izračunaj',
            'rate_label' => 'Stopa',
            'custom_label' => 'Prilagođeno',
            'custom_percent' => 'Prilagođeno %',
            'vat_label' => 'PDV (:rate%)',
            'total_incl_vat' => 'Ukupno (s PDV-om)',
            'you_entered_incl_vat' => 'Unijeli ste (s PDV-om)',
            'share_details' => 'Podijeli i detalji',
            'full_calculator' => 'Puni kalkulator',
            'eu_countries_count' => '27 država EU-a',
            'free_label' => '100% besplatno',
            'no_signup' => 'Bez registracije',
            'recent_calculations' => 'Nedavni izračuni',
            'clear_all' => 'Obriši sve',
            'show_more' => 'Prikaži još :count',
            'show_less' => 'Prikaži manje',
            'plus_vat' => '+ PDV',
            'minus_vat' => '− PDV',
        ],
        'trust' => [
            'official_ec_data' => 'Službeni podaci Europske komisije',
            'always_free' => 'Uvijek besplatno',
            'all_27_countries' => 'Svih 27 država EU-a',
            'no_signup_required' => 'Bez registracije',
        ],
    ],
    'hu' => [
        'calculator' => [
            'add_vat_mode' => 'ÁFA hozzáadása',
            'remove_vat_mode' => 'ÁFA eltávolítása',
            'realtime_rates' => 'Valós idejű adókulcsok',
            'official_eu_data' => 'Hivatalos EU adatok',
            'country_label' => 'Ország',
            'amount_incl_vat' => 'Összeg (ÁFA-val)',
            'amount_excl_vat' => 'Összeg (ÁFA nélkül)',
            'select_country' => 'Válasszon országot',
            'search_countries' => 'Országok keresése...',
            'no_countries_found' => 'Nem találhatók országok',
            'calculate_btn' => 'Számítás',
            'rate_label' => 'Adókulcs',
            'custom_label' => 'Egyéni',
            'custom_percent' => 'Egyéni %',
            'vat_label' => 'ÁFA (:rate%)',
            'total_incl_vat' => 'Összesen (ÁFA-val)',
            'you_entered_incl_vat' => 'Ön megadta (ÁFA-val)',
            'share_details' => 'Megosztás és részletek',
            'full_calculator' => 'Teljes kalkulátor',
            'eu_countries_count' => '27 EU-ország',
            'free_label' => '100% ingyenes',
            'no_signup' => 'Regisztráció nem szükséges',
            'recent_calculations' => 'Legutóbbi számítások',
            'clear_all' => 'Összes törlése',
            'show_more' => 'Még :count megjelenítése',
            'show_less' => 'Kevesebb megjelenítése',
            'plus_vat' => '+ ÁFA',
            'minus_vat' => '− ÁFA',
        ],
        'trust' => [
            'official_ec_data' => 'Az Európai Bizottság hivatalos adatai',
            'always_free' => 'Mindig ingyenes',
            'all_27_countries' => 'Mind a 27 EU-ország',
            'no_signup_required' => 'Regisztráció nem szükséges',
        ],
    ],
    'it' => [
        'calculator' => [
            'add_vat_mode' => 'Aggiungi IVA',
            'remove_vat_mode' => 'Rimuovi IVA',
            'realtime_rates' => 'Aliquote in tempo reale',
            'official_eu_data' => 'Dati ufficiali UE',
            'country_label' => 'Paese',
            'amount_incl_vat' => 'Importo (IVA inclusa)',
            'amount_excl_vat' => 'Importo (IVA esclusa)',
            'select_country' => 'Seleziona paese',
            'search_countries' => 'Cerca paesi...',
            'no_countries_found' => 'Nessun paese trovato',
            'calculate_btn' => 'Calcola',
            'rate_label' => 'Aliquota',
            'custom_label' => 'Personalizzata',
            'custom_percent' => 'Personalizzata %',
            'vat_label' => 'IVA (:rate%)',
            'total_incl_vat' => 'Totale (IVA inclusa)',
            'you_entered_incl_vat' => 'Hai inserito (IVA inclusa)',
            'share_details' => 'Condividi e dettagli',
            'full_calculator' => 'Calcolatore completo',
            'eu_countries_count' => '27 paesi UE',
            'free_label' => '100% gratuito',
            'no_signup' => 'Senza registrazione',
            'recent_calculations' => 'Calcoli recenti',
            'clear_all' => 'Cancella tutto',
            'show_more' => 'Mostra altri :count',
            'show_less' => 'Mostra meno',
            'plus_vat' => '+ IVA',
            'minus_vat' => '− IVA',
        ],
        'trust' => [
            'official_ec_data' => 'Dati ufficiali della Commissione Europea',
            'always_free' => 'Sempre gratuito',
            'all_27_countries' => 'Tutti i 27 paesi UE',
            'no_signup_required' => 'Senza registrazione',
        ],
    ],
    'lt' => [
        'calculator' => [
            'add_vat_mode' => 'Pridėti PVM',
            'remove_vat_mode' => 'Atimti PVM',
            'realtime_rates' => 'Tarifai realiu laiku',
            'official_eu_data' => 'Oficialūs ES duomenys',
            'country_label' => 'Šalis',
            'amount_incl_vat' => 'Suma (su PVM)',
            'amount_excl_vat' => 'Suma (be PVM)',
            'select_country' => 'Pasirinkite šalį',
            'search_countries' => 'Ieškoti šalių...',
            'no_countries_found' => 'Šalių nerasta',
            'calculate_btn' => 'Skaičiuoti',
            'rate_label' => 'Tarifas',
            'custom_label' => 'Pasirinktinis',
            'custom_percent' => 'Pasirinktinis %',
            'vat_label' => 'PVM (:rate%)',
            'total_incl_vat' => 'Iš viso (su PVM)',
            'you_entered_incl_vat' => 'Įvedėte (su PVM)',
            'share_details' => 'Dalintis ir detalės',
            'full_calculator' => 'Pilna skaičiuoklė',
            'eu_countries_count' => '27 ES šalys',
            'free_label' => '100% nemokamai',
            'no_signup' => 'Be registracijos',
            'recent_calculations' => 'Naujausi skaičiavimai',
            'clear_all' => 'Išvalyti viską',
            'show_more' => 'Rodyti dar :count',
            'show_less' => 'Rodyti mažiau',
            'plus_vat' => '+ PVM',
            'minus_vat' => '− PVM',
        ],
        'trust' => [
            'official_ec_data' => 'Oficialūs Europos Komisijos duomenys',
            'always_free' => 'Visada nemokamai',
            'all_27_countries' => 'Visos 27 ES šalys',
            'no_signup_required' => 'Be registracijos',
        ],
    ],
    'lv' => [
        'calculator' => [
            'add_vat_mode' => 'Pievienot PVN',
            'remove_vat_mode' => 'Noņemt PVN',
            'realtime_rates' => 'Reāllaika likmes',
            'official_eu_data' => 'Oficiāli ES dati',
            'country_label' => 'Valsts',
            'amount_incl_vat' => 'Summa (ar PVN)',
            'amount_excl_vat' => 'Summa (bez PVN)',
            'select_country' => 'Izvēlieties valsti',
            'search_countries' => 'Meklēt valstis...',
            'no_countries_found' => 'Valstis nav atrastas',
            'calculate_btn' => 'Aprēķināt',
            'rate_label' => 'Likme',
            'custom_label' => 'Pielāgota',
            'custom_percent' => 'Pielāgota %',
            'vat_label' => 'PVN (:rate%)',
            'total_incl_vat' => 'Kopā (ar PVN)',
            'you_entered_incl_vat' => 'Jūs ievadījāt (ar PVN)',
            'share_details' => 'Dalīties un detaļas',
            'full_calculator' => 'Pilns kalkulators',
            'eu_countries_count' => '27 ES valstis',
            'free_label' => '100% bezmaksas',
            'no_signup' => 'Nav nepieciešama reģistrācija',
            'recent_calculations' => 'Nesenie aprēķini',
            'clear_all' => 'Notīrīt visu',
            'show_more' => 'Rādīt vēl :count',
            'show_less' => 'Rādīt mazāk',
            'plus_vat' => '+ PVN',
            'minus_vat' => '− PVN',
        ],
        'trust' => [
            'official_ec_data' => 'Oficiāli Eiropas Komisijas dati',
            'always_free' => 'Vienmēr bezmaksas',
            'all_27_countries' => 'Visas 27 ES valstis',
            'no_signup_required' => 'Nav nepieciešama reģistrācija',
        ],
    ],
    'mt' => [
        'calculator' => [
            'add_vat_mode' => 'Żid il-VAT',
            'remove_vat_mode' => 'Neħħi l-VAT',
            'realtime_rates' => 'Rati f\'ħin reali',
            'official_eu_data' => 'Data uffiċjali tal-UE',
            'country_label' => 'Pajjiż',
            'amount_incl_vat' => 'Ammont (inkl. VAT)',
            'amount_excl_vat' => 'Ammont (eskl. VAT)',
            'select_country' => 'Agħżel pajjiż',
            'search_countries' => 'Fittex pajjiżi...',
            'no_countries_found' => 'L-ebda pajjiż instab',
            'calculate_btn' => 'Ikkalkula',
            'rate_label' => 'Rata',
            'custom_label' => 'Personalizzat',
            'custom_percent' => 'Personalizzat %',
            'vat_label' => 'VAT (:rate%)',
            'total_incl_vat' => 'Total (inkl. VAT)',
            'you_entered_incl_vat' => 'Daħħalt (inkl. VAT)',
            'share_details' => 'Aqsam u dettalji',
            'full_calculator' => 'Kalkolatur sħiħ',
            'eu_countries_count' => '27 pajjiż tal-UE',
            'free_label' => '100% b\'xejn',
            'no_signup' => 'Mingħajr reġistrazzjoni',
            'recent_calculations' => 'Kalkoli riċenti',
            'clear_all' => 'Ħassar kollox',
            'show_more' => 'Uri :count oħra',
            'show_less' => 'Uri inqas',
            'plus_vat' => '+ VAT',
            'minus_vat' => '− VAT',
        ],
        'trust' => [
            'official_ec_data' => 'Data uffiċjali tal-Kummissjoni Ewropea',
            'always_free' => 'Dejjem b\'xejn',
            'all_27_countries' => 'Is-27 pajjiż tal-UE kollha',
            'no_signup_required' => 'Mingħajr reġistrazzjoni',
        ],
    ],
    'nl' => [
        'calculator' => [
            'add_vat_mode' => 'BTW toevoegen',
            'remove_vat_mode' => 'BTW verwijderen',
            'realtime_rates' => 'Realtime tarieven',
            'official_eu_data' => 'Officiële EU-gegevens',
            'country_label' => 'Land',
            'amount_incl_vat' => 'Bedrag (incl. BTW)',
            'amount_excl_vat' => 'Bedrag (excl. BTW)',
            'select_country' => 'Selecteer land',
            'search_countries' => 'Landen zoeken...',
            'no_countries_found' => 'Geen landen gevonden',
            'calculate_btn' => 'Bereken',
            'rate_label' => 'Tarief',
            'custom_label' => 'Aangepast',
            'custom_percent' => 'Aangepast %',
            'vat_label' => 'BTW (:rate%)',
            'total_incl_vat' => 'Totaal (incl. BTW)',
            'you_entered_incl_vat' => 'U heeft ingevoerd (incl. BTW)',
            'share_details' => 'Delen & details',
            'full_calculator' => 'Volledige calculator',
            'eu_countries_count' => '27 EU-landen',
            'free_label' => '100% gratis',
            'no_signup' => 'Geen aanmelding vereist',
            'recent_calculations' => 'Recente berekeningen',
            'clear_all' => 'Alles wissen',
            'show_more' => 'Nog :count tonen',
            'show_less' => 'Minder tonen',
            'plus_vat' => '+ BTW',
            'minus_vat' => '− BTW',
        ],
        'trust' => [
            'official_ec_data' => 'Officiële gegevens van de Europese Commissie',
            'always_free' => 'Altijd gratis',
            'all_27_countries' => 'Alle 27 EU-landen',
            'no_signup_required' => 'Geen aanmelding vereist',
        ],
    ],
    'pl' => [
        'calculator' => [
            'add_vat_mode' => 'Dodaj VAT',
            'remove_vat_mode' => 'Odejmij VAT',
            'realtime_rates' => 'Stawki w czasie rzeczywistym',
            'official_eu_data' => 'Oficjalne dane UE',
            'country_label' => 'Kraj',
            'amount_incl_vat' => 'Kwota (z VAT)',
            'amount_excl_vat' => 'Kwota (bez VAT)',
            'select_country' => 'Wybierz kraj',
            'search_countries' => 'Szukaj krajów...',
            'no_countries_found' => 'Nie znaleziono krajów',
            'calculate_btn' => 'Oblicz',
            'rate_label' => 'Stawka',
            'custom_label' => 'Niestandardowa',
            'custom_percent' => 'Niestandardowa %',
            'vat_label' => 'VAT (:rate%)',
            'total_incl_vat' => 'Razem (z VAT)',
            'you_entered_incl_vat' => 'Podałeś (z VAT)',
            'share_details' => 'Udostępnij i szczegóły',
            'full_calculator' => 'Pełny kalkulator',
            'eu_countries_count' => '27 krajów UE',
            'free_label' => '100% bezpłatnie',
            'no_signup' => 'Bez rejestracji',
            'recent_calculations' => 'Ostatnie obliczenia',
            'clear_all' => 'Wyczyść wszystko',
            'show_more' => 'Pokaż jeszcze :count',
            'show_less' => 'Pokaż mniej',
            'plus_vat' => '+ VAT',
            'minus_vat' => '− VAT',
        ],
        'trust' => [
            'official_ec_data' => 'Oficjalne dane Komisji Europejskiej',
            'always_free' => 'Zawsze bezpłatnie',
            'all_27_countries' => 'Wszystkie 27 krajów UE',
            'no_signup_required' => 'Bez rejestracji',
        ],
    ],
    'pt' => [
        'calculator' => [
            'add_vat_mode' => 'Adicionar IVA',
            'remove_vat_mode' => 'Remover IVA',
            'realtime_rates' => 'Taxas em tempo real',
            'official_eu_data' => 'Dados oficiais da UE',
            'country_label' => 'País',
            'amount_incl_vat' => 'Montante (com IVA)',
            'amount_excl_vat' => 'Montante (sem IVA)',
            'select_country' => 'Selecionar país',
            'search_countries' => 'Pesquisar países...',
            'no_countries_found' => 'Nenhum país encontrado',
            'calculate_btn' => 'Calcular',
            'rate_label' => 'Taxa',
            'custom_label' => 'Personalizada',
            'custom_percent' => 'Personalizada %',
            'vat_label' => 'IVA (:rate%)',
            'total_incl_vat' => 'Total (com IVA)',
            'you_entered_incl_vat' => 'Introduziu (com IVA)',
            'share_details' => 'Partilhar e detalhes',
            'full_calculator' => 'Calculadora completa',
            'eu_countries_count' => '27 países da UE',
            'free_label' => '100% gratuito',
            'no_signup' => 'Sem registo',
            'recent_calculations' => 'Cálculos recentes',
            'clear_all' => 'Limpar tudo',
            'show_more' => 'Mostrar mais :count',
            'show_less' => 'Mostrar menos',
            'plus_vat' => '+ IVA',
            'minus_vat' => '− IVA',
        ],
        'trust' => [
            'official_ec_data' => 'Dados oficiais da Comissão Europeia',
            'always_free' => 'Sempre gratuito',
            'all_27_countries' => 'Todos os 27 países da UE',
            'no_signup_required' => 'Sem registo',
        ],
    ],
    'ro' => [
        'calculator' => [
            'add_vat_mode' => 'Adaugă TVA',
            'remove_vat_mode' => 'Elimină TVA',
            'realtime_rates' => 'Cote în timp real',
            'official_eu_data' => 'Date oficiale UE',
            'country_label' => 'Țară',
            'amount_incl_vat' => 'Sumă (cu TVA)',
            'amount_excl_vat' => 'Sumă (fără TVA)',
            'select_country' => 'Selectați țara',
            'search_countries' => 'Căutați țări...',
            'no_countries_found' => 'Nu s-au găsit țări',
            'calculate_btn' => 'Calculează',
            'rate_label' => 'Cotă',
            'custom_label' => 'Personalizată',
            'custom_percent' => 'Personalizată %',
            'vat_label' => 'TVA (:rate%)',
            'total_incl_vat' => 'Total (cu TVA)',
            'you_entered_incl_vat' => 'Ați introdus (cu TVA)',
            'share_details' => 'Partajare și detalii',
            'full_calculator' => 'Calculator complet',
            'eu_countries_count' => '27 de țări UE',
            'free_label' => '100% gratuit',
            'no_signup' => 'Fără înregistrare',
            'recent_calculations' => 'Calcule recente',
            'clear_all' => 'Șterge totul',
            'show_more' => 'Arată încă :count',
            'show_less' => 'Arată mai puțin',
            'plus_vat' => '+ TVA',
            'minus_vat' => '− TVA',
        ],
        'trust' => [
            'official_ec_data' => 'Date oficiale ale Comisiei Europene',
            'always_free' => 'Întotdeauna gratuit',
            'all_27_countries' => 'Toate cele 27 de țări UE',
            'no_signup_required' => 'Fără înregistrare',
        ],
    ],
    'sk' => [
        'calculator' => [
            'add_vat_mode' => 'Pridať DPH',
            'remove_vat_mode' => 'Odstrániť DPH',
            'realtime_rates' => 'Sadzby v reálnom čase',
            'official_eu_data' => 'Oficiálne údaje EÚ',
            'country_label' => 'Krajina',
            'amount_incl_vat' => 'Suma (s DPH)',
            'amount_excl_vat' => 'Suma (bez DPH)',
            'select_country' => 'Vyberte krajinu',
            'search_countries' => 'Hľadať krajiny...',
            'no_countries_found' => 'Žiadne krajiny nenájdené',
            'calculate_btn' => 'Vypočítať',
            'rate_label' => 'Sadzba',
            'custom_label' => 'Vlastná',
            'custom_percent' => 'Vlastná %',
            'vat_label' => 'DPH (:rate%)',
            'total_incl_vat' => 'Celkom (s DPH)',
            'you_entered_incl_vat' => 'Zadali ste (s DPH)',
            'share_details' => 'Zdieľať a podrobnosti',
            'full_calculator' => 'Plná kalkulačka',
            'eu_countries_count' => '27 krajín EÚ',
            'free_label' => '100% zadarmo',
            'no_signup' => 'Bez registrácie',
            'recent_calculations' => 'Nedávne výpočty',
            'clear_all' => 'Vymazať všetko',
            'show_more' => 'Zobraziť ďalších :count',
            'show_less' => 'Zobraziť menej',
            'plus_vat' => '+ DPH',
            'minus_vat' => '− DPH',
        ],
        'trust' => [
            'official_ec_data' => 'Oficiálne údaje Európskej komisie',
            'always_free' => 'Vždy zadarmo',
            'all_27_countries' => 'Všetkých 27 krajín EÚ',
            'no_signup_required' => 'Bez registrácie',
        ],
    ],
    'sl' => [
        'calculator' => [
            'add_vat_mode' => 'Dodaj DDV',
            'remove_vat_mode' => 'Odstrani DDV',
            'realtime_rates' => 'Stopnje v realnem času',
            'official_eu_data' => 'Uradni podatki EU',
            'country_label' => 'Država',
            'amount_incl_vat' => 'Znesek (z DDV)',
            'amount_excl_vat' => 'Znesek (brez DDV)',
            'select_country' => 'Izberite državo',
            'search_countries' => 'Iskanje držav...',
            'no_countries_found' => 'Države niso bile najdene',
            'calculate_btn' => 'Izračunaj',
            'rate_label' => 'Stopnja',
            'custom_label' => 'Po meri',
            'custom_percent' => 'Po meri %',
            'vat_label' => 'DDV (:rate%)',
            'total_incl_vat' => 'Skupaj (z DDV)',
            'you_entered_incl_vat' => 'Vnesli ste (z DDV)',
            'share_details' => 'Deli in podrobnosti',
            'full_calculator' => 'Celoten kalkulator',
            'eu_countries_count' => '27 držav EU',
            'free_label' => '100% brezplačno',
            'no_signup' => 'Brez registracije',
            'recent_calculations' => 'Nedavni izračuni',
            'clear_all' => 'Počisti vse',
            'show_more' => 'Prikaži še :count',
            'show_less' => 'Prikaži manj',
            'plus_vat' => '+ DDV',
            'minus_vat' => '− DDV',
        ],
        'trust' => [
            'official_ec_data' => 'Uradni podatki Evropske komisije',
            'always_free' => 'Vedno brezplačno',
            'all_27_countries' => 'Vseh 27 držav EU',
            'no_signup_required' => 'Brez registracije',
        ],
    ],
    'sv' => [
        'calculator' => [
            'add_vat_mode' => 'Lägg till moms',
            'remove_vat_mode' => 'Ta bort moms',
            'realtime_rates' => 'Realtidsskattesatser',
            'official_eu_data' => 'Officiella EU-data',
            'country_label' => 'Land',
            'amount_incl_vat' => 'Belopp (inkl. moms)',
            'amount_excl_vat' => 'Belopp (exkl. moms)',
            'select_country' => 'Välj land',
            'search_countries' => 'Sök länder...',
            'no_countries_found' => 'Inga länder hittades',
            'calculate_btn' => 'Beräkna',
            'rate_label' => 'Skattesats',
            'custom_label' => 'Anpassad',
            'custom_percent' => 'Anpassad %',
            'vat_label' => 'Moms (:rate%)',
            'total_incl_vat' => 'Totalt (inkl. moms)',
            'you_entered_incl_vat' => 'Du angav (inkl. moms)',
            'share_details' => 'Dela & detaljer',
            'full_calculator' => 'Fullständig kalkylator',
            'eu_countries_count' => '27 EU-länder',
            'free_label' => '100% gratis',
            'no_signup' => 'Ingen registrering krävs',
            'recent_calculations' => 'Senaste beräkningar',
            'clear_all' => 'Rensa allt',
            'show_more' => 'Visa :count till',
            'show_less' => 'Visa mindre',
            'plus_vat' => '+ moms',
            'minus_vat' => '− moms',
        ],
        'trust' => [
            'official_ec_data' => 'Officiella uppgifter från Europeiska kommissionen',
            'always_free' => 'Alltid gratis',
            'all_27_countries' => 'Alla 27 EU-länder',
            'no_signup_required' => 'Ingen registrering krävs',
        ],
    ],
];

$updated = 0;
$errors = [];

foreach ($translations as $locale => $data) {
    $filePath = "$basePath/$locale/ui.php";

    if (!file_exists($filePath)) {
        $errors[] = "File not found: $filePath";
        continue;
    }

    $content = file_get_contents($filePath);

    // Check if keys already exist
    if (str_contains($content, "'add_vat_mode'")) {
        echo "[$locale] Calculator hero keys already exist, skipping calculator keys.\n";
    } else {
        // Build the new calculator keys string
        $calcLines = [];
        foreach ($data['calculator'] as $key => $value) {
            $escaped = str_replace("'", "\\'", $value);
            $calcLines[] = "    '$key' => '$escaped',";
        }
        $calcBlock = implode("\n", $calcLines);

        // Insert after schema_app_name line
        $pattern = "/('schema_app_name'\s*=>\s*'[^']*',)\n/";
        if (preg_match($pattern, $content)) {
            $content = preg_replace(
                $pattern,
                "$1\n$calcBlock\n",
                $content,
                1
            );
            echo "[$locale] Added calculator hero keys.\n";
        } else {
            $errors[] = "[$locale] Could not find schema_app_name insertion point.";
        }
    }

    // Add trust section if not present
    if (str_contains($content, "'trust'")) {
        echo "[$locale] Trust section already exists, skipping.\n";
    } else {
        // Build trust section
        $trustLines = ["  'trust' => \n  array ("];
        foreach ($data['trust'] as $key => $value) {
            $escaped = str_replace("'", "\\'", $value);
            $trustLines[] = "    '$key' => '$escaped',";
        }
        $trustLines[] = "  ),";
        $trustBlock = implode("\n", $trustLines);

        // Insert before 'map' section
        $mapPattern = "/  'map' => \n  array \(/";
        if (preg_match($mapPattern, $content)) {
            $content = preg_replace(
                $mapPattern,
                "$trustBlock\n  'map' => \n  array (",
                $content,
                1
            );
            echo "[$locale] Added trust section.\n";
        } else {
            $errors[] = "[$locale] Could not find 'map' section for trust insertion.";
        }
    }

    file_put_contents($filePath, $content);
    $updated++;
}

echo "\n✅ Updated $updated language files.\n";
if ($errors) {
    echo "\n⚠️  Errors:\n";
    foreach ($errors as $e) {
        echo "  - $e\n";
    }
}
